// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUk2_1YQEBMBQPnYY-SxuGyaW6iruqb-o',
    appId: '1:555671953303:web:20fee71a14e7e56b012ed2',
    messagingSenderId: '555671953303',
    projectId: 'beach-party-database',
    authDomain: 'beach-party-database.firebaseapp.com',
    storageBucket: 'beach-party-database.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjksNCIQXVDGj_4CVtaosPxyRa2m45c1E',
    appId: '1:555671953303:android:0b0a402e1b2fa768012ed2',
    messagingSenderId: '555671953303',
    projectId: 'beach-party-database',
    storageBucket: 'beach-party-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVgtITZc8kSuX3Qow6zoWAeiBlIZzx2TE',
    appId: '1:555671953303:ios:51d9d4168edf65dc012ed2',
    messagingSenderId: '555671953303',
    projectId: 'beach-party-database',
    storageBucket: 'beach-party-database.appspot.com',
    iosClientId: '555671953303-81bq3hnf3r6n498hl049pg8o4jpoe3ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.beachparty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVgtITZc8kSuX3Qow6zoWAeiBlIZzx2TE',
    appId: '1:555671953303:ios:51d9d4168edf65dc012ed2',
    messagingSenderId: '555671953303',
    projectId: 'beach-party-database',
    storageBucket: 'beach-party-database.appspot.com',
    iosClientId: '555671953303-81bq3hnf3r6n498hl049pg8o4jpoe3ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.beachparty',
  );
}
